import Head from 'next/head';
import { Stack, Text } from '@chakra-ui/react';
import { Profile } from '@/componets/profile';
import { Balances } from '@/componets/balance';

export default function Home() {
	return (
		<>
			<Head>
				<title>Recycle</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Stack>
				{/* <Text>Hello World.</Text> */}
				<Profile />
				<Balances />
			</Stack>
		</>
	);
}
