import Head from 'next/head';
import { Text } from '@chakra-ui/react';
import { Profile } from '@/componets/profile';

export default function Home() {
	return (
		<>
			<Head>
				<title>Recycle</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{/* <Text>Hello World.</Text> */}
			<Profile />
		</>
	);
}
